spring:
  application:
    name: youlai-boot
  profiles:
    active: dev
  config:
    import: classpath:codegen.yml

# 在 banner.txt 中显示项目版本，使用 @project.version@ 从 pom.xml 获取
project:
  version: @project.version@
